apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  name: ansible-supervisor.fling.vsphere.vmware.com
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - config
          - kbld: {}
      export:
      - imgpkgBundle:
          image: ghcr.io/warroyo/ansible-supervisor-service
          useKbldImagesLock: true
        includePaths:
        - config
